# Generated by Django 4.2.1 on 2024-08-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_note_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='num',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='ID'),
        ),
    ]
